package olutlista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import olutlista.Humala;
import olutlista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.04 16:05:33 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HumalistoTest {



  // Generated by ComTest BEGIN
  /** testInt16 */
  @Test
  public void testInt16() {    // Humalisto: 16
    Humala hum = new Humala(); 
    assertEquals("From: Humalisto line: 19", 3, hum.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt28 */
  @Test
  public void testInt28() {    // Humalisto: 28
    Humala hum = new Humala(); 
    assertEquals("From: Humalisto line: 30", 2, hum.ekaKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString40 */
  @Test
  public void testString40() {    // Humalisto: 40
    Humala hum = new Humala(); 
    assertEquals("From: Humalisto line: 42", "Humala", hum.getKysymys(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString52 */
  @Test
  public void testString52() {    // Humalisto: 52
    Humala hum = new Humala(); 
    hum.parse("   2   |  1  |   Saaz "); 
    assertEquals("From: Humalisto line: 55", "2", hum.anna(0)); 
    assertEquals("From: Humalisto line: 56", "0", hum.anna(1)); 
    assertEquals("From: Humalisto line: 57", "1", hum.anna(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString71 */
  @Test
  public void testString71() {    // Humalisto: 71
    Humala hum = new Humala(); 
    assertEquals("From: Humalisto line: 73", null, hum.aseta(2,"Saaz")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHumalisto85 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testHumalisto85() throws CloneNotSupportedException {    // Humalisto: 85
    Humala hum = new Humala(); 
    hum.parse("   2   |  1  |   Saaz "); 
    Object kopio = hum.clone(); 
    assertEquals("From: Humalisto line: 90", hum.toString(), kopio.toString()); 
    hum.parse("   1   |  2  |   Uute "); 
    assertEquals("From: Humalisto line: 92", false, kopio.toString().equals(hum.toString())); 
    assertEquals("From: Humalisto line: 93", true, kopio instanceof Humala); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString103 */
  @Test
  public void testString103() {    // Humalisto: 103
    Humala hum = new Humala(); 
    hum.parse("   2   |  1  |   Saaz "); 
    { String _l_=hum.toString(),_r_=" 2|1 "; if ( !_l_.matches(_r_) ) fail("From: Humalisto line: 106" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}