package olutlista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import olutlista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.05 10:15:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HumalaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi74 */
  @Test
  public void testRekisteroi74() {    // Humala: 74
    Humala saaz = new Humala(); 
    assertEquals("From: Humala line: 76", 0, saaz.getTunnusNro()); 
    saaz.rekisteroi(); 
    Humala amarillo = new Humala(); 
    amarillo.rekisteroi(); 
    int n1 = saaz.getTunnusNro(); 
    int n2 = amarillo.getTunnusNro(); 
    assertEquals("From: Humala line: 82", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString124 */
  @Test
  public void testToString124() {    // Humala: 124
    Olut olut = new Olut(); 
    olut.parse(" 2 | Lapin Kulta | Lager"); 
    assertEquals("From: Humala line: 127", true, olut.toString().startsWith("2|Lapin Kulta|Lager|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse143 */
  @Test
  public void testParse143() {    // Humala: 143
    Olut olut = new Olut(); 
    olut.parse(" 2 | Lapin Kulta | Lager"); 
    assertEquals("From: Humala line: 146", 2, olut.getTunnusNro()); 
    assertEquals("From: Humala line: 147", true, olut.toString().startsWith("2|Lapin Kulta|Lager|")); 
    olut.rekisteroi(); 
    int n = olut.getTunnusNro(); 
    olut.parse (""+(n+20)); 
    olut.rekisteroi(); 
    assertEquals("From: Humala line: 153", n+20+1, olut.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta227 */
  @Test
  public void testAseta227() {    // Humala: 227
    Olut olut = new Olut(); 
    assertEquals("From: Humala line: 229", null, olut.aseta(1,"Lapin Kulta")); 
    assertEquals("From: Humala line: 230", null, olut.aseta(2,"Lager")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone264 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone264() throws CloneNotSupportedException {    // Humala: 264
    Humala hum = new Humala(); 
    hum.parse("   2   |  1  |   Saaz "); 
    Object kopio = hum.clone(); 
    assertEquals("From: Humala line: 269", hum.toString(), kopio.toString()); 
    hum.parse("   1   |  2  |   Uute "); 
    assertEquals("From: Humala line: 271", false, kopio.toString().equals(hum.toString())); 
  } // Generated by ComTest END
}