package olutlista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import kayttamattomat.Mallas;
import olutlista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.09 17:57:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MallasTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi72 */
  @Test
  public void testRekisteroi72() {    // Mallas: 72
    Mallas ohra = new Mallas(); 
    assertEquals("From: Mallas line: 74", 0, ohra.getOlutNro()); 
    ohra.rekisteroi(); 
    Mallas ohra2 = new Mallas(); 
    ohra2.rekisteroi(); 
    int n1 = ohra.getTunnusNro(); 
    int n2 = ohra2.getTunnusNro(); 
    assertEquals("From: Mallas line: 80", n2-1, n1); 
  } // Generated by ComTest END
}