package olutlista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import kayttamattomat.Mauste;
import olutlista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.09 18:21:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MausteTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi79 */
  @Test
  public void testRekisteroi79() {    // Mauste: 79
    Mauste bisse = new Mauste(); 
    assertEquals("From: Mauste line: 81", 0, bisse.getTunnusNro()); 
    bisse.rekisteroi(); 
    Mauste bisse2 = new Mauste(); 
    bisse2.rekisteroi(); 
    int n1 = bisse.getTunnusNro(); 
    int n2 = bisse2.getTunnusNro(); 
    assertEquals("From: Mauste line: 87", n2-1, n1); 
  } // Generated by ComTest END
}