package olutlista.test;
// Generated by ComTest BEGIN
import java.io.File;
import olutlista.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.05 10:16:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OluetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa57 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa57() throws SailoException {    // Oluet: 57
    Oluet oluet = new Oluet(); 
    Olut lappari = new Olut(); 
    Olut koff = new Olut(); 
    assertEquals("From: Oluet line: 62", 0, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 63", 1, oluet.getLkm()); 
    oluet.lisaa(koff); assertEquals("From: Oluet line: 64", 2, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 65", 3, oluet.getLkm()); 
    assertEquals("From: Oluet line: 66", lappari, oluet.anna(0)); 
    assertEquals("From: Oluet line: 67", koff, oluet.anna(1)); 
    assertEquals("From: Oluet line: 68", lappari, oluet.anna(2)); 
    assertEquals("From: Oluet line: 69", false, oluet.anna(1) == lappari); 
    assertEquals("From: Oluet line: 70", true, oluet.anna(1) == koff); 
    try {
    assertEquals("From: Oluet line: 71", lappari, oluet.anna(3)); 
    fail("Oluet: 71 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 72", 4, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 73", 5, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 74", 6, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 75", 7, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 76", 8, oluet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta104 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta104() throws SailoException {    // Oluet: 104
    Oluet oluet = new Oluet(); 
    Olut lappari = new Olut(); 
    Olut koff = new Olut(); 
    lappari.taytaOlut(); 
    koff.taytaOlut(); 
    String hakemisto = "testioluet"; 
    String tiedNimi = hakemisto + "/nimet"; 
    File ftied = new File(tiedNimi+ ".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    oluet.lisaa(lappari); 
    oluet.lisaa(koff); 
    oluet.talleta(); 
    oluet = new Oluet(); 
    oluet.lueTiedostosta(); 
    Iterator<Olut> i = oluet.iterator(); 
    assertEquals("From: Oluet line: 125", lappari, i.next()); 
    assertEquals("From: Oluet line: 126", koff, i.next()); 
    assertEquals("From: Oluet line: 127", false, i.hasNext()); 
    oluet.lisaa(koff); 
    oluet.talleta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testOluetIterator281 
   * @throws SailoException when error
   */
  @Test
  public void testOluetIterator281() throws SailoException {    // Oluet: 281
    Oluet oluet = new Oluet(); 
    Olut lappari = new Olut(); 
    Olut koff = new Olut(); 
    lappari.rekisteroi(); 
    koff.rekisteroi(); 
    oluet.lisaa(lappari); 
    oluet.lisaa(koff); 
    oluet.lisaa(lappari); 
    StringBuilder ids = new StringBuilder(30); 
    for (Olut olut: oluet)
    ids.append(" "+olut.getTunnusNro()); 
    String tulos = " " + lappari.getTunnusNro() + " " + koff.getTunnusNro() + " " + lappari.getTunnusNro(); 
    assertEquals("From: Oluet line: 302", tulos, ids.toString()); 
    ids = new StringBuilder(30); 
    for (Iterator<Olut>  i=oluet.iterator(); i.hasNext(); ) {
    Olut olut = i.next(); 
    ids.append(" "+olut.getTunnusNro()); 
    }
    assertEquals("From: Oluet line: 310", tulos, ids.toString()); 
    Iterator<Olut>  i=oluet.iterator(); 
    assertEquals("From: Oluet line: 313", true, i.next() == lappari); 
    assertEquals("From: Oluet line: 314", true, i.next() == koff); 
    assertEquals("From: Oluet line: 315", true, i.next() == lappari); 
    try {
    i.next(); 
    fail("Oluet: 317 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi378 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi378() throws SailoException {    // Oluet: 378
    Oluet oluet = new Oluet(); 
    Olut olut1 = new Olut(); olut1.parse("1|Lapin Kulta|Lager|ohramallas|"); 
    Olut olut2 = new Olut(); olut2.parse("2|Koff||ohra|"); 
    Olut olut3 = new Olut(); olut3.parse("3|Karhu|Lager||saaz|4,5"); 
    Olut olut4 = new Olut(); olut4.parse("4|Karjala|Lager|ohra"); 
    Olut olut5 = new Olut(); olut5.parse("5|Kukko|Lager|ohra"); 
    oluet.lisaa(olut1); oluet.lisaa(olut2); oluet.lisaa(olut3); oluet.lisaa(olut4); oluet.lisaa(olut5); 
  } // Generated by ComTest END
}