package olutlista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import olutlista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.23 10:56:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OluetTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa30 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa30() throws SailoException {    // Oluet: 30
    Oluet oluet = new Oluet(); 
    Olut lappari = new Olut(); 
    Olut koff = new Olut(); 
    assertEquals("From: Oluet line: 35", 0, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 36", 1, oluet.getLkm()); 
    oluet.lisaa(koff); assertEquals("From: Oluet line: 37", 2, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 38", 3, oluet.getLkm()); 
    assertEquals("From: Oluet line: 39", lappari, oluet.anna(0)); 
    assertEquals("From: Oluet line: 40", koff, oluet.anna(1)); 
    assertEquals("From: Oluet line: 41", lappari, oluet.anna(2)); 
    assertEquals("From: Oluet line: 42", false, oluet.anna(1) == lappari); 
    assertEquals("From: Oluet line: 43", true, oluet.anna(1) == koff); 
    try {
    assertEquals("From: Oluet line: 44", lappari, oluet.anna(3)); 
    fail("Oluet: 44 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 45", 4, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 46", 5, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 47", 6, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 48", 7, oluet.getLkm()); 
    oluet.lisaa(lappari); assertEquals("From: Oluet line: 49", 8, oluet.getLkm()); 
    try {
    oluet.lisaa(lappari); 
    fail("Oluet: 50 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}