package olutlista.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import olutlista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.09 17:59:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OlutlistaTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa42 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa42() throws SailoException {    // Olutlista: 42
    Olutlista olutlista = new Olutlista(); 
    Olut lappari = new Olut(); 
    Olut koff = new Olut(); 
    lappari.rekisteroi(); 
    koff.rekisteroi(); 
    assertEquals("From: Olutlista line: 49", 0, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 50", 1, olutlista.getOluet()); 
    olutlista.lisaa(koff); assertEquals("From: Olutlista line: 51", 2, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 52", 3, olutlista.getOluet()); 
    assertEquals("From: Olutlista line: 53", 3, olutlista.getOluet()); 
    assertEquals("From: Olutlista line: 54", lappari, olutlista.annaOlut(0)); 
    assertEquals("From: Olutlista line: 55", koff, olutlista.annaOlut(1)); 
    assertEquals("From: Olutlista line: 56", lappari, olutlista.annaOlut(2)); 
    try {
    assertEquals("From: Olutlista line: 57", lappari, olutlista.annaOlut(3)); 
    fail("Olutlista: 57 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 58", 4, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 59", 5, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 60", 6, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 61", 7, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 62", 8, olutlista.getOluet()); 
    try {
    olutlista.lisaa(lappari); 
    fail("Olutlista: 63 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaMaltaat102 */
  @Test
  public void testAnnaMaltaat102() {    // Olutlista: 102
    Olutlista olutlista = new Olutlista(); 
    Olut lappari = new Olut(); 
    Olut koff = new Olut(); 
    Olut karhu = new Olut(); 
    lappari.rekisteroi(); 
    koff.rekisteroi(); 
    karhu.rekisteroi(); 
    int id1= lappari.getTunnusNro(); 
    int id2 = koff.getTunnusNro(); 
    Mallas ohra11 = new Mallas(id1); olutlista.lisaa(ohra11); 
    Mallas ohra12 = new Mallas(id1); olutlista.lisaa(ohra12); 
    Mallas ohra21 = new Mallas(id2); olutlista.lisaa(ohra21); 
    Mallas ohra22 = new Mallas(id2); olutlista.lisaa(ohra22); 
    Mallas ohra23 = new Mallas(id2); olutlista.lisaa(ohra23); 
    List<Mallas>loytyneet; 
    loytyneet = olutlista.annaMaltaat(karhu); 
    assertEquals("From: Olutlista line: 122", 0, loytyneet.size()); 
    loytyneet = olutlista.annaMaltaat(lappari); 
    assertEquals("From: Olutlista line: 124", 2, loytyneet.size()); 
    assertEquals("From: Olutlista line: 125", true, loytyneet.get(0) == ohra11); 
    assertEquals("From: Olutlista line: 126", true, loytyneet.get(1) == ohra12); 
    loytyneet = olutlista.annaMaltaat(koff); 
    assertEquals("From: Olutlista line: 128", 3, loytyneet.size()); 
    assertEquals("From: Olutlista line: 129", true, loytyneet.get(0) == ohra21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaHumalat141 */
  @Test
  public void testAnnaHumalat141() {    // Olutlista: 141
    Olutlista olutlista = new Olutlista(); 
    Olut lappari = new Olut(); 
    Olut koff = new Olut(); 
    Olut karhu = new Olut(); 
    lappari.rekisteroi(); 
    koff.rekisteroi(); 
    karhu.rekisteroi(); 
    int id1= lappari.getTunnusNro(); 
    int id2 = koff.getTunnusNro(); 
    Humala saaz11 = new Humala(id1); olutlista.lisaa(saaz11); 
    Humala saaz12 = new Humala(id1); olutlista.lisaa(saaz12); 
    Humala saaz21 = new Humala(id2); olutlista.lisaa(saaz21); 
    Humala saaz22 = new Humala(id2); olutlista.lisaa(saaz22); 
    Humala saaz23 = new Humala(id2); olutlista.lisaa(saaz23); 
    List<Humala>loytyneet; 
    loytyneet = olutlista.annaHumalat(karhu); 
    assertEquals("From: Olutlista line: 161", 0, loytyneet.size()); 
    loytyneet = olutlista.annaHumalat(lappari); 
    assertEquals("From: Olutlista line: 163", 2, loytyneet.size()); 
    assertEquals("From: Olutlista line: 164", true, loytyneet.get(0) == saaz11); 
    assertEquals("From: Olutlista line: 165", true, loytyneet.get(1) == saaz12); 
    loytyneet = olutlista.annaHumalat(koff); 
    assertEquals("From: Olutlista line: 167", 3, loytyneet.size()); 
    assertEquals("From: Olutlista line: 168", true, loytyneet.get(0) == saaz21); 
  } // Generated by ComTest END
}