package olutlista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import olutlista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.07 13:07:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OlutlistaTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa61 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa61() throws SailoException {    // Olutlista: 61
    Olutlista olutlista = new Olutlista(); 
    Olut lappari = new Olut(); 
    Olut koff = new Olut(); 
    lappari.rekisteroi(); 
    koff.rekisteroi(); 
    assertEquals("From: Olutlista line: 68", 0, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 69", 1, olutlista.getOluet()); 
    olutlista.lisaa(koff); assertEquals("From: Olutlista line: 70", 2, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 71", 3, olutlista.getOluet()); 
    assertEquals("From: Olutlista line: 72", 3, olutlista.getOluet()); 
    assertEquals("From: Olutlista line: 73", lappari, olutlista.annaOlut(0)); 
    assertEquals("From: Olutlista line: 74", koff, olutlista.annaOlut(1)); 
    assertEquals("From: Olutlista line: 75", lappari, olutlista.annaOlut(2)); 
    try {
    assertEquals("From: Olutlista line: 76", lappari, olutlista.annaOlut(3)); 
    fail("Olutlista: 76 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 77", 4, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 78", 5, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 79", 6, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 80", 7, olutlista.getOluet()); 
    olutlista.lisaa(lappari); assertEquals("From: Olutlista line: 81", 8, olutlista.getOluet()); 
  } // Generated by ComTest END
}